# Generated by Django 5.0.1 on 2024-01-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_alter_chat_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Custom User'},
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Johnson Masino', max_length=200),
        ),
    ]
