# Generated by Django 5.0.1 on 2024-01-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
