# Generated by Django 5.0.1 on 2024-01-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_profile_full_name_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
