# Generated by Django 5.0.1 on 2024-01-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Custom User'},
        ),
    ]
